path_classifiers:
  external:
    - "cmake"
    - "packages/kokkos"
    - "packages/zoltan"
    - "packages/seacas/libraries/ioss/src/visualization"
  test:
    - "SEACAS-Test"
  docs:
    - "docs"
    - "packages/seacas/doc-source"
