image: Visual Studio 2017

environment:
  matrix:
    - TARGET_ARCH: x64
      CONDA_INSTALL_LOCN: C:\\Miniconda-x64
      MSYS2_INSTALL_LOCN: C:\msys64
      MSYS2_BIN_LOCN: C:\msys64\usr\bin
      CMAKE_GENERATOR: "Visual Studio 15 Win64"
      SUPPRESSIONS: "/wd4478"
      VCPKG_DEFAULT_TRIPLET: "x64-windows"
      VCPKG_BUILD_TYPE: "release"
      LIB_ROOT: C:\Tools\vcpkg\installed\%VCPKG_DEFAULT_TRIPLET%

platform:
    - x64

branches:
  except:
    - /.*[.]dmh/
    - /.*[.]wif/

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

install:
  - cmd: set SRC_DIR=%cd%
  - cmd: set INSTALL_LOC=%SRC_DIR%\install
  - cmd: set PATH=%PATH%;%MSYS2_BIN_LOCN%;%INSTALL_LOC%\bin;%INSTALL_LOC%\lib
  - cmd: vcpkg install netcdf-c
  - cmd: vcpkg install matio
  - cmd: vcpkg integrate install

configuration: Release

build: off

# Run a custom script.
build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake .. -G "%CMAKE_GENERATOR%" ^
     -DBUILD_SHARED_LIBS:BOOL=OFF ^
     -DCMAKE_BUILD_TYPE=Release ^
     -DCMAKE_CXX_FLAGS="%SUPPRESSIONS% /EHsc" ^
     -DCMAKE_C_FLAGS="%SUPPRESSIONS%" ^
     -DCMAKE_INSTALL_PREFIX=%INSTALL_LOC% ^
     -DHDF5_ROOT:PATH=%LIB_ROOT% ^
     -DHDF5_LIBRARY:PATH=%LIB_ROOT%\lib\libhdf5.lib
     -DHDF5_INCLUDE_DIRS:PATH=%LIB_ROOT%\include ^
     -DHDF5_LIBRARIES:PATH=%LIB_ROOT%\lib\libhdf5_hl.lib;%LIB_ROOT%\lib\libhdf5.lib ^
     -DHDF5_C_LIBRARIES:PATH=%LIB_ROOT%\lib\libhdf5.lib ^
     -DHDF5_HL_LIBRARIES:PATH=%LIB_ROOT%\lib\libhdf5_hl.lib ^
     -DMatio_INCLUDE_DIRS:PATH=%LIB_ROOT%\include ^
     -DMatio_LIBRARIES:PATH=%LIB_ROOT%\lib\libmatio.lib ^
     -DNetCDF_ROOT:PATH=%LIB_ROOT% ^
     -DSEACASExodus_ENABLE_THREADSAFE:BOOL=OFF ^
     -DSEACASIoss_ENABLE_THREADSAFE:BOOL=OFF ^
     -DSEACASProj_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON ^
     -DSEACASProj_ENABLE_ALL_PACKAGES:BOOL=ON ^
     -DSEACASProj_ENABLE_DOXYGEN:BOOL=OFF ^
     -DSEACASProj_ENABLE_Fortran=OFF ^
     -DSEACASProj_ENABLE_SEACAS:BOOL=ON ^
     -DSEACASProj_ENABLE_SECONDARY_TESTED_CODE:BOOL=ON ^
     -DSEACASProj_ENABLE_TESTS=ON ^
     -DSEACASProj_ENABLE_Zoltan:BOOL=OFF ^
     -DSEACASProj_HIDE_DEPRECATED_CODE:BOOL=ON ^
     -DSEACASProj_SKIP_FORTRANCINTERFACE_VERIFY_TEST:BOOL=ON ^
     -DTPL_ENABLE_ADIOS2:BOOL=OFF ^
     -DTPL_ENABLE_CGNS:BOOL=OFF ^
     -DTPL_ENABLE_Kokkos:BOOL=OFF ^
     -DTPL_ENABLE_MPI:BOOL=OFF ^
     -DTPL_ENABLE_Matio:BOOL=ON ^
     -DTPL_ENABLE_Netcdf:BOOL=ON ^
     -DTPL_ENABLE_Pamgen:BOOL=OFF ^
     -DTPL_ENABLE_Pthread:BOOL=OFF ^
     -DTPL_ENABLE_X11:BOOL=OFF ^
     -DTPL_ENABLE_gtest:BOOL=OFF

  - cmd: if errorlevel 1 exit 1
  - cmd: cmake --build . --verbose --config %configuration% -- /maxcpucount:4

test_script:
  - cmd: ctest
