image: Visual Studio 2017

environment:
  matrix:
    - TARGET_ARCH: x64
      CONDA_INSTALL_LOCN: C:\\Miniconda-x64
      MSYS2_INSTALL_LOCN: C:\msys64
      MSYS2_BIN_LOCN: C:\msys64\usr\bin
      CMAKE_GENERATOR: "Visual Studio 15 Win64"
      SUPPRESSIONS: "/wd4478"
      VCPKG_DEFAULT_TRIPLET: "x64-windows"
      VCPKG_BUILD_TYPE: "release"
      LIB_ROOT: "C:\Tools\vcpkg\installed\x64-windows"

platform:
    - x64

branches:
  except:
    - /.*[.]dmh/
    - /.*[.]wif/

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

install:
  - cmd: set SRC_DIR=%cd%
  - cmd: set INSTALL_LOC=%SRC_DIR%\install
  - cmd: set PATH=%PATH%;%MSYS2_BIN_LOCN%;%INSTALL_LOC%\bin;%INSTALL_LOC%\lib
  - cmd: vcpkg install netcdf-c
  - cmd: vcpkg install matio
  - cmd: vcpkg integrate install
    
configuration: Release

build: off

# Run a custom script.
build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake .. -G "%CMAKE_GENERATOR%" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%INSTALL_LOC% -DSEACASProj_ENABLE_SEACAS:BOOL=ON -DSEACASProj_ENABLE_ALL_PACKAGES:BOOL=ON -DSEACASProj_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON -DSEACASProj_ENABLE_SECONDARY_TESTED_CODE:BOOL=ON -D BUILD_SHARED_LIBS:BOOL=OFF -D SEACASProj_ENABLE_Zoltan:BOOL=OFF -D SEACASProj_ENABLE_TESTS=ON  -D SEACASProj_SKIP_FORTRANCINTERFACE_VERIFY_TEST:BOOL=ON -D SEACASProj_HIDE_DEPRECATED_CODE:BOOL=ON -D SEACASProj_ENABLE_DOXYGEN:BOOL=OFF -D SEACASProj_ENABLE_Fortran=OFF -D TPL_ENABLE_Netcdf:BOOL=ON -D TPL_ENABLE_Matio:BOOL=ON -D TPL_ENABLE_CGNS:BOOL=OFF -D TPL_ENABLE_ADIOS2:BOOL=OFF -D TPL_ENABLE_gtest:BOOL=OFF -D TPL_ENABLE_Kokkos:BOOL=OFF -D TPL_ENABLE_MPI:BOOL=OFF -D TPL_ENABLE_Pamgen:BOOL=OFF -D TPL_ENABLE_Pthread:BOOL=OFF -D TPL_ENABLE_X11:BOOL=OFF -D SEACASExodus_ENABLE_THREADSAFE:BOOL=OFF -D SEACASIoss_ENABLE_THREADSAFE:BOOL=OFF -DCMAKE_CXX_FLAGS="%SUPPRESSIONS% /EHsc" -DCMAKE_C_FLAGS="%SUPPRESSIONS%" -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DMatio_ROOT:PATH=%LIB_ROOT% -DMatio_DIR:PATH=%LIB_ROOT% -DNetCDF_ROOT:PATH=%LIB_ROOT% -DHDF5_ROOT:PATH=%LIB_ROOT%

  - cmd: if errorlevel 1 exit 1
  - cmd: cmake --build . --config Release -- /maxcpucount:4

test_script:
  - cmd: ctest 